### PR TITLE
changed RUN mongo-cxx-driver to point to releases/v3.2 and not releas…

### PR DESCRIPTION
**Pull request by isamuelson**
…es/stable

releases/stable was updated and now requires mongo-c-driver-1.10.0 and above.

### CODE REVIEW

**Comment by heifner** [comment]
Thanks for this, but merged #4100 which includes this.

**Comment by trungtt1981** [comment]
@isamuelson 
@heifner 
According to your suggestion, I've changed `releases/stable` to `releases/v3.2 ` in the script `eosio_build_ubuntu.sh`. 

This is really helpful in overcoming the error:
`Build failed: No compatible configuration file for package "libbson-static-1.0"`

However, the build on my `Ubuntu 16.04` is still eventually failed with the following error:

```
............
../libbsoncxx-testing.a(validate.cpp.o): In function `bsoncxx::v_noabi::validator::~validator()':
validate.cpp:(.text+0x39): undefined reference to `operator delete(void*)'
../libbsoncxx-testing.a(validate.cpp.o):(.eh_frame+0xfb): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
src/bsoncxx/test/CMakeFiles/test_bson.dir/build.make:304: recipe for target 'src/bsoncxx/test/test_bson' failed
make[2]: *** [src/bsoncxx/test/test_bson] Error 1
CMakeFiles/Makefile2:602: recipe for target 'src/bsoncxx/test/CMakeFiles/test_bson.dir/all' failed
make[1]: *** [src/bsoncxx/test/CMakeFiles/test_bson.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 26%] Building CXX object src/mongocxx/CMakeFiles/mongocxx_mocked.dir/cursor.cpp.o
[ 26%] Building CXX object src/mongocxx/CMakeFiles/mongocxx.dir/index_model.cpp.o
[ 27%] Building CXX object src/mongocxx/CMakeFiles/mongocxx.dir/index_view.cpp.o
[ 27%] Building CXX object src/mongocxx/CMakeFiles/mongocxx_mocked.dir/database.cpp.o
.................
[ 70%] Building CXX object src/mongocxx/CMakeFiles/mongocxx_mocked.dir/validation_criteria.cpp.o
[ 70%] Building CXX object src/mongocxx/CMakeFiles/mongocxx_mocked.dir/write_concern.cpp.o
[ 72%] Linking CXX static library libmongocxx-static.a
[ 72%] Built target mongocxx
[ 72%] Linking CXX static library libmongocxx-mocked.a
[ 72%] Built target mongocxx_mocked
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
	Error compiling MongoDB C++ driver.

	Exiting now.
```
Look forward to your help!
