### PR TITLE
Make compatible with boost 1.67+

### PR DESCRIPTION
**Pull request by heifner**
## Change Description

- Remove use of make_strand to make compatible with boost 1.67+
- Add `async_teardown` impl for < 1.70 of boost

## Change Type
**Select *ONE*:**
- [ ] Documentation

- [ ] Stability bug fix

- [x] Other

- [ ] Other - special case

## Testing Changes
**Select *ANY* that apply:**
- [ ] New Tests

- [x] Existing Tests

- [ ] Test Framework

- [ ] CI System

- [ ] Other

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

- Documentation that boost 1.68 and 1.67 official releases need patches on some platforms.

### CODE REVIEW

**Comment by spoonincode** [comment]
I'm seeing another problem in addition to the make_strand

```
plugins/state_history_plugin/state_history_plugin.cpp:352:34:   required from ‘void eosio::state_history_plugin_impl::ws_session<SocketType>::start_read() [with SocketType = boost::asio::basic_stream_socket<boost::asio::local::stream_protocol>]’
plugins/state_history_plugin/state_history_plugin.cpp:327:42:   required from ‘void eosio::state_history_plugin_impl::ws_session<SocketType>::start() [with SocketType = boost::asio::basic_stream_socket<boost::asio::local::stream_protocol>]’
plugins/state_history_plugin/state_history_plugin.cpp:440:18:   required from ‘void eosio::state_history_plugin_impl::session_manager_t::add(eosio::state_history_plugin_impl*, std::shared_ptr<_Tp>) [with SocketType = boost::asio::basic_stream_socket<boost::asio::local::stream_protocol>]’
plugins/state_history_plugin/state_history_plugin.cpp:534:25:   required from ‘void eosio::state_history_plugin_impl::do_accept(Acceptor&) [with Acceptor = boost::asio::basic_socket_acceptor<boost::asio::local::stream_protocol>]’
plugins/state_history_plugin/state_history_plugin.cpp:519:16:   required from here
boost167/include/boost/beast/websocket/teardown.hpp:103:33: error: static assertion failed: Unknown Socket type in async_teardown.
  103 |     static_assert(sizeof(Socket)==-1,

```

**Comment by praphael** [comment]
I get this error when compiling Ubuntu 20.04 (unpinned, gcc), with boost 1.67

`In file included from /root/eos/libraries/chain/include/eosio/chain/name.hpp:5,
                 from /root/eos/libraries/chain/include/eosio/chain/types.hpp:2,
                 from /root/eos/libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/eos-vm-oc.hpp:3,
                 from /root/eos/libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/code_cache.hpp:5,
                 from /root/eos/libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp:4:
/root/eos/libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp: In constructor ‘eosio::chain::eosvmoc::code_cache_base::code_cache_base(boost::filesystem::path, const eosio::chain::eosvmoc::config&, eosio::chain::eosvmoc::code_cache_base::code_finder)’:
/root/eos/libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp:348:25: warning: comparison of integer expressions of different signedness: ‘std::streamsize’ {aka ‘long int’} and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
  348 |       EOS_ASSERT(copied >= on_disk_size, database_exception, "Failed to preload code cache memory");
      |                  ~~~~~~~^~~~~~~~~~~~~~~
/root/eos/libraries/chain/include/eosio/chain/exceptions.hpp:9:10: note: in definition of macro ‘EOS_ASSERT’
    9 |    if( !(expr) )                                                      \
      |          ^~~~
In file included from /root/eos/libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/code_cache.hpp:3,
                 from /root/eos/libraries/chain/webassembly/runtimes/eos-vm-oc/executor.cpp:2:
/boost_1_67_0/boost/lockfree/spsc_queue.hpp: In member function ‘ConstIterator boost::lockfree::detail::ringbuffer_base<T>::push(ConstIterator, ConstIterator, T*, boost::lockfree::detail::ringbuffer_base<T>::size_t)’:
/boost_1_67_0/boost/lockfree/spsc_queue.hpp:140:43: error: ‘next’ is not a member of ‘boost’
  140 |         const ConstIterator last = boost::next(begin, input_count);
      |                                           ^~~~`

**Comment by heifner** [comment]
> I get this error when compiling Ubuntu 20.04 (unpinned, gcc), with boost 1.67
> 
> boost::lockfree::detail::ringbuffer_base<T>::size_t)’: /boost_1_67_0/boost/lockfree/spsc_queue.hpp:140:43: error: ‘next’ is not a member of ‘boost’ 140 | const ConstIterator last = boost::next(begin, input_count); | ^~~~`

This is a known bug in 1.67. I patched my 1.67 to get around it.

**Comment by spoonincode** [comment]
There is more on that particular error (and why we decided not to carry a fix in eosio for it) over at #9673

**Comment by praphael** [comment]
> There is more on that particular error (and why we decided not to carry a fix in eosio for it) over at #9673

Is there a patch for a generic boost install ? My testing d/ls from official boost release ... they don't seem to mention a patch for this specific issue.  https://www.boost.org/users/history/version_1_67_0.html There are patches for other issue.  Not sure if there is an unofficial patch somewhere.

**Comment by spoonincode** [comment]
If you click through to the patch Debian is using, that works.

**Comment by heifner** [comment]
I did this: https://github.com/MusicPlayerDaemon/MPD/pull/266/files

**Comment by praphael** [comment]
How about these, trying to build with boost 1.68 

`In file included from /boost_1_68_0/boost/test/data/monomorphic.hpp:18,
                 from /boost_1_68_0/boost/test/data/dataset.hpp:16,
                 from /boost_1_68_0/boost/test/data/test_case.hpp:17,
                 from /root/eos/build.boost168/eosio-wasm-spec-tests/generated-tests/include/wasm_spec_tests.hpp:3,
                 from /root/eos/eosio-wasm-spec-tests/generated-tests/address.cpp:1:
/boost_1_68_0/boost/test/data/monomorphic/initializer_list.hpp:45:27: error: ‘vector’ in namespace ‘std’ does not name a template type
   45 |     typedef typename std::vector<T>::const_iterator iterator;
      |                           ^~~~~~
/boost_1_68_0/boost/test/data/monomorphic/initializer_list.hpp:21:1: note: ‘std::vector’ is defined in header ‘<vector>’; did you forget to ‘#include <vector>’?

Looks to me like we are missing an include of `<vector>` in `dataset.hpp`. We often have to add extra includes for gcc.

**Comment by spoonincode** [comment]
Looks like 1.68 was broken there
```
https://github.com/boostorg/test/issues/150
```

**Review by praphael — APPROVED** [review]
Approved.   We may want to add in documentation that 1.68 and 1.67 official releases need patches.
