### ISSUE TITLE
'float.h' file not found when I include <eosio/chain/types.hpp>

### ISSUE THREAD

**Issue by thbourlove** [EOSIO/eos#4513]
```
vagrant@ubuntu-xenial:/vagrant$ eosiocpp -o mycontract.wast mycontract.cpp
In file included from mycontract.cpp:5:
In file included from ./mycontract.hpp:8:
In file included from /usr/local/include/eosio/chain/types.hpp:6:
In file included from /usr/local/include/eosio/chain/name.hpp:3:
In file included from /usr/local/include/fc/reflect/reflect.hpp:10:
In file included from /home/vagrant/opt/boost/include/boost/lexical_cast.hpp:32:
In file included from /home/vagrant/opt/boost/include/boost/lexical_cast/try_lexical_convert.hpp:42:
In file included from /home/vagrant/opt/boost/include/boost/lexical_cast/detail/converter_lexical.hpp:54:
In file included from /home/vagrant/opt/boost/include/boost/lexical_cast/detail/converter_lexical_streams.hpp:63:
In file included from /home/vagrant/opt/boost/include/boost/lexical_cast/detail/inf_nan.hpp:34:
In file included from /home/vagrant/opt/boost/include/boost/math/special_functions/sign.hpp:16:
In file included from /home/vagrant/opt/boost/include/boost/math/tools/config.hpp:21:
In file included from /usr/local/include/libc++/upstream/include/cfloat:64:
/usr/local/include/libc++/upstream/include/float.h:69:15: fatal error: 'float.h' file
      not found
#include_next <float.h>
              ^~~~~~~~~
1 error generated.
```

**Comment by thbourlove** [comment]
#1931 #4350

**Comment by andriantolie** [comment]
You shouldn't include any `eosio/chain/*` inside your smart contract, it won't be supported. The right types.hpp for a smart contract is `#include <eosio/types.hpp>` which is the file inside contracts/eosiolib/types.hpp

**Comment by nirdesh365** [comment]
I included the file #include <eosio/types.hpp> yet is found the same error in 'float.h' file
 not found  #include_next <float.h>

**Comment by JohnnyZhao** [comment]
same issue here.

using docker build using Docker/dev/Dockerfile v1.2.3, got this error when I try to include: 

```
#include <fc/variant_object.hpp>
```

the image I use: `eoslaomao/eos-dev:1.2.3`

any ideas?
