### ISSUE TITLE
Dawn 4.0 mongo_db_plugin does't work

### ISSUE THREAD

**Issue by red-butterfly** [EOSIO/eos#3030]
The mongo_db_plugin does't work in EOS Dawn 4.0:

2629991ms thread-0   main.cpp:101                  main                 ] /mnt/500G/project/blockchain/EOS/eos-4.0/libraries/appbase/application.cpp(290): Throw in function appbase::abstract_plugin &appbase::application::get_plugin(const string &) const
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: unable to find plugin: eosio::mongo_db_plugin

**Comment by yankeeyu** [comment]
I've got exactly same issue [here (issue#3018)](https://github.com/EOSIO/eos/issues/3018)

**Comment by rise-worlds** [comment]
change CMakeLists.txt mongo_db_plugin compile error
`[100%] Building CXX object plugins/mongo_db_plugin/CMakeFiles/mongo_db_plugin.dir/mongo_db_plugin.cpp.o
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:134:31: error: no member named 'block' in 'eosio::chain::block_trace'
         process_block(bt, bt.block);
                           ~~ ^
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:137:63: error: no member named 'block' in 'eosio::chain::block_trace'
         block_trace_queue.emplace_back(std::make_pair(bt, bt.block));
                                                           ~~ ^
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:406:42: error: no member named 'receiver' in 'eosio::chain::action_trace'
                     kvp("receiver", act.receiver.to_string()),
                                     ~~~ ^
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:410:38: error: no member named 'data_access' in 'eosio::chain::action_trace'
         for (const auto& data : act.data_access) {
                                 ~~~ ^
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:412:62: error: no member named 'data_access_info' in namespace 'eosio::chain'
               subdoc.append(kvp("type", data.type == chain::data_access_info::read ? "read" : "write"),
                                                      ~~~~~~~^
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:466:28: error: no member named 'region_traces' in 'eosio::chain::block_trace'
   for (const auto& rt: bt.region_traces) {
                        ~~ ^
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:477:28: error: no template named 'contains'; did you mean 'boost::contains'?
                  if ( req.contains<chain::deferred_transaction>() ) {
                           ^~~~~~~~
                           boost::contains
/home/server123/opt/boost_1_66_0/include/boost/algorithm/string/predicate.hpp:464:22: note: 'boost::contains' declared here
    using algorithm::contains;
                     ^
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:478:68: error: expected '(' for function-style cast or type construction
                     auto trx = req.get<chain::deferred_transaction>();
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:478:70: error: expected expression
                     auto trx = req.get<chain::deferred_transaction>();
                                                                     ^
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:489:69: error: expected '(' for function-style cast or type construction
                     auto cancel = req.get<chain::deferred_reference>();
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:489:71: error: expected expression
                     auto cancel = req.get<chain::deferred_reference>();
                                                                      ^
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:519:40: error: no member named 'input_transactions' in 'eosio::chain::signed_block'; did you mean 'transactions'?
   for (const auto& packed_trx : block.input_transactions) {
                                       ^~~~~~~~~~~~~~~~~~
                                       transactions
/home/server123/eos/libraries/chain/include/eosio/chain/block.hpp:58:37: note: 'transactions' declared here
      vector<transaction_receipt>   transactions; /// new or generated transactions
                                    ^
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:520:50: error: no member named 'get_signed_transaction' in 'eosio::chain::transaction_receipt'
      const signed_transaction& trx = packed_trx.get_signed_transaction();
                                      ~~~~~~~~~~ ^
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:533:39: error: no member named 'implicit_transactions' in 'eosio::chain::block_trace'
   for (const auto& implicit_trx : bt.implicit_transactions ){
                                   ~~ ^
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:592:30: error: no member named 'regions' in 'eosio::chain::signed_block'
   for (const auto& r: block.regions) {
                       ~~~~~ ^
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:831:34: error: no member named 'applied_block_callbacks' in 'eosio::chain::controller::config'
      chain_plug->chain_config().applied_block_callbacks.emplace_back(
      ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/home/server123/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:833:34: error: no member named 'applied_irreversible_block_callbacks' in 'eosio::chain::controller::config'
      chain_plug->chain_config().applied_irreversible_block_callbacks.emplace_back(
      ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
17 errors generated.
plugins/mongo_db_plugin/CMakeFiles/mongo_db_plugin.dir/build.make:62: recipe for target 'plugins/mongo_db_plugin/CMakeFiles/mongo_db_plugin.dir/mongo_db_plugin.cpp.o' failed
make[2]: *** [plugins/mongo_db_plugin/CMakeFiles/mongo_db_plugin.dir/mongo_db_plugin.cpp.o] Error 1
CMakeFiles/Makefile2:5547: recipe for target 'plugins/mongo_db_plugin/CMakeFiles/mongo_db_plugin.dir/all' failed
make[1]: *** [plugins/mongo_db_plugin/CMakeFiles/mongo_db_plugin.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.
`

**Comment by paritygeeker** [comment]
programs/nodeos/CMakeLists.txt:60
the code have been commented。
so will not make the target object.
And added db_size_api_plugin, so there will be something change on database.

**Comment by rise-worlds** [comment]
@ripley use the new sql_db_plugin

**Comment by ripley** [comment]
@rise-worlds 
Thank you for the info, I just took a quick look at the files under directory plugins/sql_db_plugin, seems most of the them are skeletons for now. Did you successfully poll data and save to db via the plugin?

**Comment by trungtt1981** [comment]
I've got the same error although in Ubuntu the MongoDB plugin is compiled and built by default.
I'm at this commit ID on master branch `cd21f12e539452ff405729a4bf8bde0391172264`
My nodeos version:

```
nodeos -v
3441553710
```

**Comment by andrei-anisimov** [comment]
Do you plan to enable the mongo_db_plugin? If I understand it correctly, without it there is no way to explore transactions (other than through the limited history API).

**Comment by noprom** [comment]
Maybe this PR will solve this: https://github.com/EOSIO/eos/pull/4304

**Comment by heifner** [comment]
@noprom that is the idea. Try it out and let us know.

**Comment by noprom** [comment]
@heifner , will try that out immediately.

**Comment by gustavomick** [comment]
@heifner hi, wondering if there is a way to rebase this branch to have the mongo plugin isolated from other changes, or if you can suggest a way to merge this with 1.0.8 version. thanks!

**Comment by noprom** [comment]
HI @gustavomick, you can try our docker image to setup the mongo in 5 seconds:
https://github.com/EOSpace/eos-sync

**Comment by gustavomick** [comment]
@heifner is mongo plugin filtering using filter-on config.ini setting? is there a way to filter? thanks

**Comment by heifner** [comment]
- I just rebased with release/1.1.
- There is currently no filter capability. What kind of filter capability are you interested in? A filter of which collections get populated?

**Comment by gustavomick** [comment]
@heifner thanks , yeah i would like to know if is possible to filter using the config.ini filter-on parameter, i think is really handy for dapp that has a full node and only whant specific transactions on their  history (like only those related to the dapps contract) so together with that history filtering should be very useful that mongoplugin would be replicating only those in the same fashion. or is other way to do that? thanks!

**Comment by jrosich** [comment]
agreed with @gustavomick

**Comment by wanderingbort** [comment]
see #4304

**Comment by heifner** [comment]
brief of changes:

The optional `eosio::mongo_db_plugin` provides archiving of blockchain data into a MongoDB. It is recommended that the plugin be added to a non-producing node as it is designed to shut down on any failed insert into the MongoDB and is resource intensive. The rationale behind this shutdown on error is so that any issues with the mongo database or connectivity can be fixed and the nodeos can be restarted without having to resync or replay.

The `mongo_db_plugin` does slow down replay/resync as the conversion of block data to JSON and insertion into MongoDB is resource intensive. The plugin does use a worker thread for processing the block data, but this does not help much when replaying/resyncing. 

It is recommended that a large `--abi-serializer-max-time-ms` value be passed into the nodeos running the `mongo_db_plugin` as the default abi serializer time limit is not large enough to serialize large blocks. 

The following mongo collections are created:
- accounts - created on accepted transaction
-- Currently limited to just name and ABI if contract on account
-- Mostly for internal use as the stored ABI is used to convert action data into JSON for storage as associated actions on contract are processed.
-- Invalid ABI on account will prevent conversion of action data into JSON for storage resulting in just the action data being stored as hex. For example, the original eosio.system contract did not provide ABI for the `onblock` action and therefore all 'onblock` action data is stored as hex until the time `onblock` ABI is added to the eosio.system contract.

- actions - created on accepted transaction
-- action_num - the # of the action in its transaction
-- trx_id
-- account
-- name
-- authorization
--- actor
--- permission
-- data
-- hex_data

- block_states - created on accepted block
-- block_num
-- block_id
-- block_header_state
-- validated
-- in_current_chain

- blocks - created on accepted block
-- block_num
-- block_id
-- irreversible - updated to true on irreversible block
-- block

- transaction_traces - created on applied transaction
-- transaction_trace

- transactions - created on accepted transaction
-- trx_id
-- irreversible - updated to true on irreversible block
-- transaction_header
-- signing_keys
-- actions
-- context_free_actions
-- transaction_extensions
-- signatures
-- context_free_data
