### ISSUE TITLE
Ubuntu18.04 build failed!

### ISSUE THREAD

**Issue by jiangshangqifeng** [EOSIO/eos#9319]
Hi there
I built eos on Ubuntu18.04 and it's failed:

```
$ ./scripts/eosio_build.sh 
EOSIO Version: 2.0.7
2020年 07月 18日 星期六 03:35:10 UTC
User: jht
Current branch: master
No installation location was specified. Please provide the location where EOSIO is installed.
Do you wish to use the default location? /home/jht/eosio/2.0? (y/n) y

EOSIO will be installed to: /home/jht/eosio/2.0
=====================================================================================
======================= Starting EOSIO Dependency Install ===========================
Architecture: Linux
OS name: Ubuntu
OS Version: 18.04
CPU cores: 4
Physical Memory: 12G
Disk space total: 171G
Disk space available: 140G
[Ensuring package dependencies]
 - git ok
 - make ok
 - bzip2 ok
 - automake ok
 - libbz2-dev ok
 - libssl-dev ok
 - doxygen ok
 - graphviz ok
 - libgmp3-dev ok
 - autotools-dev ok
 - libicu-dev ok
 - python2.7 ok
 - python2.7-dev ok
 - python3 ok
 - python3-dev ok
 - autoconf ok
 - libtool ok
 - curl ok
 - zlib1g-dev ok
 - sudo ok
 - ruby ok
 - libusb-1.0-0-dev ok
 - libcurl4-gnutls-dev ok
 - pkg-config ok
 - patch ok
 - clang ok
 - llvm-7-dev ok
 - No required package dependencies to install.



[Ensuring CMAKE installation]
 - CMAKE found @ /usr/local/bin/cmake.

[Ensuring Boost 1.71.0 library installation]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 95.4M  100 95.4M    0     0  2017k      0  0:00:48  0:00:48 --:--:-- 2296k
Building Boost.Build engine with toolset gcc... 
Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details
```
and bootstrap.log show:

```
###
###
### Using 'gcc' toolset.
###
###
clang++ --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
###
###
clang++ -x c++ -std=c++11 -O2 -s -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execc
md.cpp filesys.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jambase.cpp jamgram.cpp lists.cpp
make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathsys.cpp regexp.cpp rules.cpp scan.
cpp search.cpp strings.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/prope
rty-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp execunix.cpp fileunix.cpp pathunix.cpp -o b2
sysinfo.cpp:10:10: fatal error: 'thread' file not found
#include <thread>
         ^~~~~~~~
1 error generated.
```

can somebody help me?

**Comment by aclark-b1** [comment]
It looks like clang can't find the standard C++ library headers, do you have an alternate library installed?  Can you please try to build on a clean 18.04 box and see if you can reproduce the issue?  Our build system does this multiple times per day and we haven't seen this behavior.
