### ISSUE TITLE
Unable to build docker image

### ISSUE THREAD

**Issue by Swaagie** [EOSIO/eos#60]
Tried to docker build on OSX Sierra with Docker CE 17.06.0-ce-mac18. The build failed on
```
[ 95%] Linking CXX executable chain_test
CMakeFiles/chain_test.dir/tests/simplecoin.cpp.o: In function `onInit':
/eos/tests/tests/simplecoin.cpp:(.text+0xf): undefined reference to `name_to_int64'
CMakeFiles/chain_test.dir/tests/simplecoin.cpp.o: In function `apply_simplecoin_transfer':
/eos/tests/tests/simplecoin.cpp:(.text+0xce): undefined reference to `assert'
CMakeFiles/chain_test.dir/tests/simplecoin.cpp.o: In function `void store<long long, Balance>(long long const&, Balance const&)':
/eos/tests/tests/simplecoin.cpp:(.text._Z5storeIx7BalanceEvRKT_RKT0_[_Z5storeIx7BalanceEvRKT_RKT0_]+0x2d): undefined reference to `store'
CMakeFiles/chain_test.dir/tests/simplecoin.cpp.o: In function `void readMessage<Transfer>(Transfer&)':
/eos/tests/tests/simplecoin.cpp:(.text._Z11readMessageI8TransferEvRT_[_Z11readMessageI8TransferEvRT_]+0x16): undefined reference to `readMessage'
CMakeFiles/chain_test.dir/tests/simplecoin.cpp.o: In function `int load<long long, Balance>(long long const&, Balance&)':
/eos/tests/tests/simplecoin.cpp:(.text._Z4loadIx7BalanceEiRKT_RT0_[_Z4loadIx7BalanceEiRKT_RT0_]+0x2d): undefined reference to `load'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
tests/CMakeFiles/chain_test.dir/build.make:350: recipe for target 'tests/chain_test' failed
make[2]: *** [tests/chain_test] Error 1
CMakeFiles/Makefile2:2152: recipe for target 'tests/CMakeFiles/chain_test.dir/all' failed
make[1]: *** [tests/CMakeFiles/chain_test.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
Inspection of the docker images showed the following tools were used.
```
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
clang version 4.0.1-svn305187-1~exp1 (branches/release_40)
```
Thoughts to get the build to work that I can verify?

**Comment by lionello** [comment]
This'll fix it https://github.com/EOSIO/eos/pull/62

**Comment by Swaagie** [comment]
This was fixed with the latest master
